title: Hydure
tagline: A concise two-column blog theme for jekyll

cover: cover.jpg

author:
  name: Song-Zi Vong
  url: https://twitter.com/zivong91

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag

paginate: 3
